# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import top_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('top_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=top_blog.models.blogimages_directory)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_blog.Blog')),
            ],
        ),
    ]
